# -*- coding: utf-8 -*-
"""Trimester 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_54M0WPc7n3_1sWFV3XInR05cuBB34f
"""

# ============================================================================
# DIGIT PROJECT - Complete Analysis Code for Google Colab
# District Government Implementation Governance Index & Tracking
#
# Author: Vedant Manna
# Roll Number: 23035010206
# School of Data Science & Artificial Intelligence, IIT Guwahati
# ============================================================================

# Run this code in Google Colab to reproduce all visualizations

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from io import StringIO
import warnings
warnings.filterwarnings('ignore')

# Set style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (16, 12)
plt.rcParams['font.size'] = 10

# ============================================================================
# STEP 1: LOAD DATA
# ============================================================================
print("=" * 80)
print("DIGIT PROJECT - ANALYSIS AND VISUALIZATION")
print("=" * 80)

# Option A: Upload CSV file (uncomment to use)
# from google.colab import files
# uploaded = files.upload()
# df = pd.read_csv(list(uploaded.keys())[0])

# Option B: Use raw CSV data (copy-paste from file)
csv_data = """District,Revenue_Allocated_Lakhs,Works_Planned,Works_Completed,Works_Pending,Completion_Rate_%,Revenue_Utilized_Lakhs,Revenue_Returned_Lakhs,Utilization_Rate_%
Lucknow,850,45,42,3,93.33,701.17,148.83,82.49
Kanpur Nagar,720,38,35,3,92.11,676.9,43.1,94.01
Ghaziabad,680,42,38,4,90.48,609.55,70.45,89.64
Allahabad,620,36,32,4,88.89,484.35,135.65,78.12
Varanasi,590,35,31,4,88.57,513.14,76.86,86.97
Bareilly,550,32,28,4,87.5,478.62,71.38,87.02
Meerut,640,39,34,5,87.18,499.97,140.03,78.12
Agra,630,38,33,5,86.84,479.82,150.18,76.16
Noida,600,36,31,5,86.11,553.94,46.06,92.32
Moradabad,520,28,24,4,85.71,463.64,56.36,89.16
Mathura,500,28,24,4,85.71,411.64,88.36,82.33
Saharanpur,470,25,21,4,84.0,410.01,59.99,87.24
Budaun,460,24,20,4,83.33,384.74,75.26,83.64
Bijnor,440,22,18,4,81.82,355.63,84.37,80.82
Jaunpur,420,22,18,4,81.82,316.73,103.27,75.41
Hapur,320,16,13,3,81.25,248.93,71.07,77.79
Gorakhpur,480,26,21,5,80.77,453.11,26.89,94.4
Azamgarh,410,20,16,4,80.0,375.76,34.24,91.65
Ballia,350,15,12,3,80.0,275.34,74.66,78.67
Firozabad,380,19,15,4,78.95,319.66,60.34,84.12
Deoria,340,14,11,3,78.57,275.69,64.31,81.09
Shamli,280,14,11,3,78.57,226.36,53.64,80.84
Sultanpur,380,18,14,4,77.78,301.14,78.86,79.25
Ambedkar Nagar,360,17,13,4,76.47,283.09,76.91,78.64
Kushinagar,310,12,9,3,75.0,265.03,44.97,85.49"""

# Load data from CSV string
df = pd.read_csv(StringIO(csv_data))

print("\n✓ Data loaded successfully!")
print(f"✓ Districts analyzed: {len(df)}")
print(f"\nFirst few rows:\n{df.head()}")

# ============================================================================
# STEP 2: CALCULATE SUMMARY STATISTICS
# ============================================================================

print("\n" + "=" * 80)
print("SUMMARY STATISTICS")
print("=" * 80)

total_allocated = df['Revenue_Allocated_Lakhs'].sum()
total_utilized = df['Revenue_Utilized_Lakhs'].sum()
total_returned = df['Revenue_Returned_Lakhs'].sum()
overall_utilization = (total_utilized / total_allocated * 100)

total_planned = df['Works_Planned'].sum()
total_completed = df['Works_Completed'].sum()
total_pending = df['Works_Pending'].sum()
overall_completion = (total_completed / total_planned * 100)

print(f"\nREVENUE METRICS:")
print(f"  Total Allocated: ₹{total_allocated:,.0f} Lakhs")
print(f"  Total Utilized: ₹{total_utilized:,.0f} Lakhs")
print(f"  Total Returned: ₹{total_returned:,.0f} Lakhs")
print(f"  Overall Utilization: {overall_utilization:.2f}%")

print(f"\nWORK COMPLETION METRICS:")
print(f"  Total Planned: {total_planned} works")
print(f"  Total Completed: {total_completed} works")
print(f"  Total Pending: {total_pending} works")
print(f"  Overall Completion: {overall_completion:.2f}%")

# Top and Bottom performers
print(f"\nTOP 5 PERFORMERS (by Completion Rate):")
top_5 = df.nlargest(5, 'Completion_Rate_%')
for idx, (_, row) in enumerate(top_5.iterrows(), 1):
    print(f"  {idx}. {row['District']:<20} → {row['Completion_Rate_%']:.2f}%")

print(f"\nBOTTOM 5 PERFORMERS (by Completion Rate):")
bottom_5 = df.nsmallest(5, 'Completion_Rate_%')
for idx, (_, row) in enumerate(bottom_5.iterrows(), 1):
    print(f"  {idx}. {row['District']:<20} → {row['Completion_Rate_%']:.2f}%")

# Correlation analysis
correlation = df['Completion_Rate_%'].corr(df['Utilization_Rate_%'])
print(f"\nCORRELATION ANALYSIS:")
print(f"  Pearson Correlation (Completion vs Utilization): {correlation:.3f}")
print(f"  Interpretation: Weak to moderate positive correlation")

# ============================================================================
# STEP 3: CREATE VISUALIZATIONS (6 CHARTS)
# ============================================================================

print("\n" + "=" * 80)
print("GENERATING VISUALIZATIONS")
print("=" * 80)

fig = plt.figure(figsize=(18, 14))
from matplotlib.gridspec import GridSpec
gs = GridSpec(3, 2, figure=fig, hspace=0.3, wspace=0.25)

# Chart 1: Top vs Bottom Districts - Completion Rate
print("\n1. Generating: Top 5 & Bottom 5 Districts by Completion Rate...")
ax1 = fig.add_subplot(gs[0, 0])
top_bottom_comp = pd.concat([top_5, bottom_5])
colors = ['#2ecc71']*5 + ['#e74c3c']*5
bars = ax1.barh(top_bottom_comp['District'], top_bottom_comp['Completion_Rate_%'], color=colors)
ax1.set_xlabel('Completion Rate (%)', fontweight='bold')
ax1.set_title('Top 5 & Bottom 5 Districts by Work Completion Rate', fontweight='bold', fontsize=12)
ax1.axvline(overall_completion, color='blue', linestyle='--', linewidth=2, label=f'Overall Avg: {overall_completion:.1f}%')
ax1.legend()
for i, v in enumerate(top_bottom_comp['Completion_Rate_%']):
    ax1.text(v + 0.5, i, f'{v:.1f}%', va='center')

# Chart 2: Top vs Bottom Districts - Revenue Utilization
print("2. Generating: Top 5 & Bottom 5 Districts by Revenue Utilization...")
ax2 = fig.add_subplot(gs[0, 1])
top_5_util = df.nlargest(5, 'Utilization_Rate_%')
bottom_5_util = df.nsmallest(5, 'Utilization_Rate_%')
top_bottom_util = pd.concat([top_5_util, bottom_5_util])
colors = ['#3498db']*5 + ['#e67e22']*5
bars = ax2.barh(top_bottom_util['District'], top_bottom_util['Utilization_Rate_%'], color=colors)
ax2.set_xlabel('Utilization Rate (%)', fontweight='bold')
ax2.set_title('Top 5 & Bottom 5 Districts by Revenue Utilization', fontweight='bold', fontsize=12)
ax2.axvline(overall_utilization, color='red', linestyle='--', linewidth=2, label=f'Overall Avg: {overall_utilization:.1f}%')
ax2.legend()
for i, v in enumerate(top_bottom_util['Utilization_Rate_%']):
    ax2.text(v + 0.5, i, f'{v:.1f}%', va='center')

# Chart 3: Revenue Allocation vs Utilization by District
print("3. Generating: Top 10 Districts - Allocated vs Utilized Revenue...")
ax3 = fig.add_subplot(gs[1, 0])
df_sorted = df.sort_values('Revenue_Allocated_Lakhs', ascending=False).head(10)
x = np.arange(len(df_sorted))
width = 0.35
ax3.bar(x - width/2, df_sorted['Revenue_Allocated_Lakhs'], width, label='Allocated', color='#9b59b6')
ax3.bar(x + width/2, df_sorted['Revenue_Utilized_Lakhs'], width, label='Utilized', color='#1abc9c')
ax3.set_xlabel('Districts', fontweight='bold')
ax3.set_ylabel('Revenue (Lakhs)', fontweight='bold')
ax3.set_title('Top 10 Districts: Allocated vs Utilized Revenue', fontweight='bold', fontsize=12)
ax3.set_xticks(x)
ax3.set_xticklabels(df_sorted['District'], rotation=45, ha='right', fontsize=9)
ax3.legend()
ax3.grid(axis='y', alpha=0.3)

# Chart 4: Works Planned vs Completed by District
print("4. Generating: Top 10 Districts - Works Planned vs Completed...")
ax4 = fig.add_subplot(gs[1, 1])
df_works = df.sort_values('Works_Planned', ascending=False).head(10)
x = np.arange(len(df_works))
width = 0.35
ax4.bar(x - width/2, df_works['Works_Planned'], width, label='Planned', color='#f39c12')
ax4.bar(x + width/2, df_works['Works_Completed'], width, label='Completed', color='#27ae60')
ax4.set_xlabel('Districts', fontweight='bold')
ax4.set_ylabel('Number of Works', fontweight='bold')
ax4.set_title('Top 10 Districts: Works Planned vs Completed', fontweight='bold', fontsize=12)
ax4.set_xticks(x)
ax4.set_xticklabels(df_works['District'], rotation=45, ha='right', fontsize=9)
ax4.legend()
ax4.grid(axis='y', alpha=0.3)

# Chart 5: Correlation: Completion Rate vs Utilization Rate
print("5. Generating: Correlation Analysis - Completion vs Utilization...")
ax5 = fig.add_subplot(gs[2, 0])
scatter = ax5.scatter(df['Completion_Rate_%'], df['Utilization_Rate_%'],
                      s=df['Revenue_Allocated_Lakhs']*2, alpha=0.6, c=df['Completion_Rate_%'], cmap='RdYlGn')
ax5.set_xlabel('Work Completion Rate (%)', fontweight='bold')
ax5.set_ylabel('Revenue Utilization Rate (%)', fontweight='bold')
ax5.set_title('Correlation: Completion Rate vs Revenue Utilization\n(bubble size = revenue allocated)', fontweight='bold', fontsize=12)
ax5.grid(True, alpha=0.3)
cbar = plt.colorbar(scatter, ax=ax5)
cbar.set_label('Completion %', fontweight='bold')

# Chart 6: Revenue Performance Summary (Pie)
print("6. Generating: Overall Revenue Performance Pie Chart...")
ax6 = fig.add_subplot(gs[2, 1])
utilization_data = [total_utilized, total_returned]
colors_pie = ['#2ecc71', '#e74c3c']
wedges, texts, autotexts = ax6.pie(utilization_data, labels=['Utilized', 'Returned'], autopct='%1.1f%%',
                                     colors=colors_pie, startangle=90, textprops={'fontweight': 'bold'})
ax6.set_title(f'Overall Revenue Performance\nTotal Allocated: ₹{total_allocated:.0f} Lakhs', fontweight='bold', fontsize=12)
for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontsize(11)

# Add main title
plt.suptitle('Uttar Pradesh - District-wise Government Works Analysis Report',
             fontsize=16, fontweight='bold', y=0.995)

plt.tight_layout()
print("\n✓ All 6 charts generated successfully!")
print("\nDISPLAYING DASHBOARD...")

# Save the figure BEFORE showing it
plt.savefig('DIGIT_Analysis_Dashboard.png', dpi=300, bbox_inches='tight')
print("✓ Dashboard saved as 'DIGIT_Analysis_Dashboard.png'")

plt.show()

# ============================================================================
# STEP 4: GENERATE DETAILED REPORT
# ============================================================================

print("\n" + "=" * 80)
print("DETAILED ANALYSIS REPORT")
print("=" * 80)

print(f"""
OVERALL STATISTICS:
══════════════════════════════════════════════════════════════════════════════
Total Districts Analyzed:              {len(df)}
Total Revenue Allocated:               ₹{total_allocated:,.0f} Lakhs
Total Revenue Utilized:                ₹{total_utilized:,.0f} Lakhs
Total Revenue Returned (Unspent):      ₹{total_returned:,.0f} Lakhs
Overall Budget Utilization Rate:       {overall_utilization:.2f}%

Total Works Planned:                   {total_planned}
Total Works Completed:                 {total_completed}
Total Works Pending:                   {total_pending}
Overall Project Completion Rate:       {overall_completion:.2f}%

Performance Gap (Top vs Bottom):        {top_5['Completion_Rate_%'].iloc[0] - bottom_5['Completion_Rate_%'].iloc[0]:.2f} percentage points
Correlation (Completion vs Util):      {correlation:.3f}
""")

print("\nTOP 10 DISTRICTS BY COMPLETION RATE:")
print("─" * 80)
top_10 = df.nlargest(10, 'Completion_Rate_%')
for idx, (_, row) in enumerate(top_10.iterrows(), 1):
    print(f"{idx:2}. {row['District']:<20} {row['Completion_Rate_%']:>7.2f}% " +
          f"({int(row['Works_Completed'])}/{int(row['Works_Planned'])} works)")

print("\nBOTTOM 10 DISTRICTS BY COMPLETION RATE:")
print("─" * 80)
bottom_10 = df.nsmallest(10, 'Completion_Rate_%')
for idx, (_, row) in enumerate(bottom_10.iterrows(), 1):
    print(f"{idx:2}. {row['District']:<20} {row['Completion_Rate_%']:>7.2f}% " +
          f"({int(row['Works_Completed'])}/{int(row['Works_Planned'])} works)")

print("\nTOP 10 DISTRICTS BY BUDGET UTILIZATION RATE:")
print("─" * 80)
top_10_util = df.nlargest(10, 'Utilization_Rate_%')
for idx, (_, row) in enumerate(top_10_util.iterrows(), 1):
    print(f"{idx:2}. {row['District']:<20} {row['Utilization_Rate_%']:>7.2f}% " +
          f"(₹{row['Revenue_Utilized_Lakhs']:,.0f}/₹{row['Revenue_Allocated_Lakhs']:,.0f} Lakhs)")

print("\nBOTTOM 10 DISTRICTS BY BUDGET UTILIZATION RATE:")
print("─" * 80)
bottom_10_util = df.nsmallest(10, 'Utilization_Rate_%')
for idx, (_, row) in enumerate(bottom_10_util.iterrows(), 1):
    unspent = row['Revenue_Returned_Lakhs']
    print(f"{idx:2}. {row['District']:<20} {row['Utilization_Rate_%']:>7.2f}% " +
          f"(₹{unspent:,.0f} Lakhs unspent)")

# ============================================================================
# STEP 5: EXPORT RESULTS
# ============================================================================

print("\n" + "=" * 80)
print("EXPORTING RESULTS")
print("=" * 80)

# Save full data
df.to_csv('DIGIT_Full_Analysis.csv', index=False)
print("✓ Full analysis data exported: DIGIT_Full_Analysis.csv")

# Create summary statistics file
summary_stats = pd.DataFrame({
    'Metric': [
        'Total Districts',
        'Total Revenue Allocated (Lakhs)',
        'Total Revenue Utilized (Lakhs)',
        'Total Revenue Returned (Lakhs)',
        'Overall Utilization Rate (%)',
        'Total Works Planned',
        'Total Works Completed',
        'Total Works Pending',
        'Overall Completion Rate (%)',
        'Average Completion Rate (%)',
        'Average Utilization Rate (%)',
        'Correlation (Completion vs Utilization)',
        'Max Completion Rate (%)',
        'Min Completion Rate (%)',
        'Performance Gap (%)'
    ],
    'Value': [
        len(df),
        total_allocated,
        total_utilized,
        total_returned,
        overall_utilization,
        total_planned,
        total_completed,
        total_pending,
        overall_completion,
        df['Completion_Rate_%'].mean(),
        df['Utilization_Rate_%'].mean(),
        correlation,
        df['Completion_Rate_%'].max(),
        df['Completion_Rate_%'].min(),
        top_5['Completion_Rate_%'].iloc[0] - bottom_5['Completion_Rate_%'].iloc[0]
    ]
})

summary_stats.to_csv('DIGIT_Summary_Statistics.csv', index=False)
print("✓ Summary statistics exported: DIGIT_Summary_Statistics.csv")

# ============================================================================
# FINAL SUMMARY
# ============================================================================

print("\n" + "=" * 80)
print("ANALYSIS COMPLETE!")
print("=" * 80)
print("""
✓ Data Analysis:        Completed
✓ Statistical Analysis: Completed
✓ Visualizations:       6 Charts Generated
✓ Dashboard:            Saved as 'DIGIT_Analysis_Dashboard.png'
✓ Data Export:          CSV files created

FILES GENERATED:
  1. DIGIT_Analysis_Dashboard.png     - Main visualization dashboard
  2. DIGIT_Full_Analysis.csv          - Complete data with calculations
  3. DIGIT_Summary_Statistics.csv     - Key metrics summary

KEY FINDINGS:
  • Overall Completion Rate:    {:.2f}%
  • Overall Utilization Rate:   {:.2f}%
  • Unspent Budget:             ₹{:,.0f} Lakhs
  • Performance Gap:            {:.2f} percentage points
  • Correlation Coefficient:    {:.3f}

NEXT STEPS:
  1. Review the visualizations above
  2. Check the exported CSV files
  3. Use these insights for your IIT Guwahati presentation

For questions or modifications, refer to the code comments above.
""".format(overall_completion, overall_utilization, total_returned,
          top_5['Completion_Rate_%'].iloc[0] - bottom_5['Completion_Rate_%'].iloc[0],
          correlation))

print("=" * 80)

